### PR TITLE
Standardize the typography for links

### PR DESCRIPTION
**Pull request by kmarekspartz**
- Use verbs at the beginning of each phrase.
- Use `.` at the end of each phrase.
- Namedrop GitHub like we namedrop Google Sheets.
- Put GitHub link on its own line, after the email link.
- Make GitHub link to the README.md rather than the repository root for easier reading by people less familiar with GitHub.
- Autoremove some unneeded whitespace.

Before:

image

After:

image

### CODE REVIEW

**Comment by kmarekspartz** [comment]
I'm wondering about pulling `See this data in Google Sheets.` down, too.

**Comment by kmarekspartz** [comment]
I like that the spreadsheet link is there directly for those that are less familiar with coding.

How is this?

image

**Comment by mc-funk** [comment]
@samanpwbb we can't move the link to the spreadsheet into the README -- we have users who expect to be able to reference it easily and they're definitely not going to GitHub for it.
I like keeping it up top with the others at bottom, FWIW

**Comment by kmarekspartz** [comment]
OK, I won't push my latest screenshot then, though removing the spaced-lines class helped a bit. I'll try just that change.

**Comment by kmarekspartz** [comment]
New revision: image

**Comment by samanpwbb** [comment]
I think this is definitely good enough to merge now, but I'd like to make a quick suggestion for you to take or leave:

Screen Shot 2020-06-03 at 5 36 41 PM

**Comment by mc-funk** [comment]
@samanpwbb we really need to not value conciseness or white space over usability. Our users are often not in the tech space so being explicit and clear is more important than being concise. I think the revision as it stands is clearer for our users.

**Comment by samanpwbb** [comment]
I agree with you – my concern is that usability has taken a real hit due to the size of the top section. Here's what the map looks like on an iPhone SE. The map is not really usable any more:

Screen Shot 2020-06-03 at 6 14 22 PM

**Comment by mc-funk** [comment]
@samanpwbb that's a great point. Can you create a new issue for the usability issue? I have a feeling that a collapsible legend might be needed, since collapsing links doesn't really buy us much space at the end of the day.

**Comment by kmarekspartz** [comment]
Could we completely hide the links other than email on small screens?

**Pull request merged**
