### PR TITLE
Track filters and sort in google analytics

### LINKED ISSUE #158: Tweak search functionality on aid map to allow Google Analytics to pick up search terms
Currently there is no way for GA to track what users are searching for in the new search feature.
OOTB GA functionality relies on URL query parameters passing search terms and filters, which doesn't seem like an option here.
Can we get a global variable to pass search terms in the current set up? Or other options that Tag Manager can grab?

### PR DESCRIPTION
**Pull request by crhistianramirez**
### What
Track filter and sort events in google analytics. Closes #158

### Why
Gives us better insight into how users are using our app so we can make better decisions about features

### Ensure the following interactions work as expected. Please test using a mobile form factor.
- [x] Tapping on a marker on the map displays information about the marker in a popup.
- [x] Tapping the "Show list of locations" button replaces the map view with a list view.
- [x] Tapping an item in the list replaces the list view with a map view, and navigates the map to the tapped item on the map.
- [x] Tapping one of the ✅'s in the legend filters items on the map and in the list.
- [x] Changing the language to spanish changes things on the page.
- [x] Clicking the Help/Info button opens and closes a menu with information.
- [x] Clicking the X Close button on the Help/Info screen closes the modal.

### Check the app in the following web browsers:
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari

### CODE REVIEW

**Comment by crhistianramirez** [comment]
@echoseekererer I updated the code per your suggestions.

> it's also important we track the copy users see for the label

If the user has a different language selected, then this value will be the translated text in whatever language they selected. I thought that might mess up your analytics so that's why I was using the other value instead. If not, cool but just wanted to make sure you were aware.

**Comment by echoseekererer** [comment]
> If the user has a different language selected, then this value will be the translated text in whatever language they selected. I thought that might mess up your analytics so that's why I was using the other value instead. If not, cool but just wanted to make sure you were aware.

@crhistianramirez good point and thank you for saving me more work later :)
How about:

> Event Category: _Search Filter_
> Event Action: _Check/Uncheck_
> Event Label: _[input value]: [label]_ so _receiving: open for receiving donations_

Screenshot 2020-06-19 at 11 18 09 AM
(Noticed there's a typo on the element above, too. Dunno how complicated that is to fix.)

Also, Event Category and Event Action are still transposed. Can you switch those values?
Screenshot 2020-06-19 at 10 49 12 AM

**Comment by experimatt** [comment]
@crhistianramirez is this ready for re-review/merge? let us know :)

**Comment by jdalt** [comment]
@echoseekererer @crhistianramirez I took the liberty of trying to clear up the remaining issues with this. If could give it a nod fo approval, we should be ready to merge it.

**Comment by crhistianramirez** [comment]
@echoseekererer @jdalt 

Sorry for not communicating better, I was moving out of my apartment this week.

I went ahead and updated the PR to include the language-agnostic value

**Comment by echoseekererer** [comment]
> @echoseekererer @jdalt
> 
> Sorry for not communicating better, I was moving out of my apartment this week.
> 
> I went ahead and updated the PR to include the language-agnostic value so should be ready for review again

@crhistianramirez np, hope your move went well!
This looks great. Thanks, all, pretty excited for this shiny new data :D

**Pull request merged**
