### PR TITLE
Pull to refresh

### PR DESCRIPTION
**Pull request by amaxama**
### What
Add pull to refresh functionality for mobile and remove the refresh button. Since all web browsers have a visible refresh button built in, it's not required to include is as an explicit button on the page. Also, pull-to-refresh is a fairly intuitive action on mobile devices so should be pretty natural fo most users.

### Why
Opens up screen real estate

### Ensure the following interactions work as expected. Please test using a mobile form factor.
- [x] Tapping on a marker on the map displays information about the marker in a popup.
- [x] Tapping the "Show list of locations" button replaces the map view with a list view.
- [x] Tapping an item in the list replaces the list view with a map view, and navigates the map to the tapped item on the map.
- [x] Tapping one of the ✅'s in the legend filters items on the map and in the list.
- [x] Changing the language to spanish changes things on the page.
- [x] Clicking the Help/Info button opens and closes a menu with information.
- [x] Clicking the X Close button on the Help/Info screen closes the modal.

### Check the app in the following web browsers:
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [x] Safari

### CODE REVIEW

**Comment by amaxama** [comment]
Video is a little laggy but the general idea is there...
pull-to-refresh

**Comment by amaxama** [comment]
Visual of screen realestate with the refresh button:

Screen Shot 2020-10-01 at 12 32 40 AM

Without the refresh button:
Screen Shot 2020-10-01 at 12 34 29 AM

**Comment by mc-funk** [comment]
Sorry it took me so long to get to this. 
So, the history of the refresh button is that it created a solution for folks who would keep the site open too long and the data would be stale, so we added the refresh button so that folks could have a cue that they could ensure the data were up to date. It's been a while, so I'm not sure who we were getting the staleness concerns from, but it seems like if it had been intuitive to those folks to just refresh the page we wouldn't have added the button. On the other hand, it's possible that use cases or user familiarity have changed and it isn't needed anymore, or that it was never even used in the first place. I'd definitely be interested in asking on the TCMAP side what folks think about that (I assume we don't have tracking on the refresh button?). 

Will give this a test on mobile tomorrow. Do you have any thoughts on how you think we'd want to communicate to users that this feature was available? It's something folks expect on feeds etc., but especially with our panel being static I don't think that's something I'd think to try personally.  Do you think

**Comment by amaxama** [comment]
@mc-funk Thanks for reviewing!! 
Yeah, I get that rationale (one reason I was a little hesitant to make this change but I felt that the screen real estate was worth it...)...but based on google analytics - the average session duration is about 2-3 minutes...and that stays pretty consistent over the past week, 30 days, 90 days...occasionally a session here and there will get up to 10-15 min and only 5 times in the past 2 months has it crossed 30 min (which honestly, I wouldn't be surprised if a couple of those were me haha). This change is also only relevant on mobile where I feel like it's less likely that users are spending long periods of time on the map in one session..
It looks like we do not have tracking on the button, unfortunately. I could add it, but would probably take a while for us to get any helpful metrics. I can float it to TCMAP to get others' thoughts!

Re: communicating to folks... for Android users - pull to refresh on webpages is pretty second nature on chrome (I couldn't actually find any other than ours that didn't have it built in...). For iphone users...it's also less imperative that they know it's a built-in feature becasue safari has the refresh button visibly in the browserbar by default.... however, I was thinking it could be the subject of a maptip monday maybe?

**Comment by amaxama** [comment]
@mc-funk feedback from TCMAP is this can be approved 👍 anything else you'd like me to adjust in the PR?

**Review by mc-funk — APPROVED** [review]
LG!

**Pull request merged**
