### PR TITLE
Karen Language

### PR DESCRIPTION
**Pull request by benjifs**
I got the translations for Karen this morning and thought this would be an easier add. The [KNU font](https://www.spps.org/Page/15801) used by the translators added a new layer to this since we'd need to support custom fonts for some languages. I had previously already added an `html lang="xxx"` to the page since I figured it might be useful to have and with that we are able to apply styles to elements that have `data-translation-id`. For items that need that font but dont get translated (`moment.js` text), I added a `data-translate-font` to have the font applied to that without it trying to be translated.

That works fine but there's a few issues I've run into:

1. The font that we're using seems to be messing with text from `moment` since this font also changes numbers to characters from the font. I'm not sure if the end result is the same or if the `last_updated` results are incorrect.
2. If there are no translations (currently `search`, `clear_search`, and `list_results` in Karen have no translations), the font is still applied and the end result is that "Search" is still written out with the `KNU` font.

An alternative which I'm not sure if it would work would be to use a different font which supports Unicode. I found this: http://lixwa.com/info/. With that we'd still need to add the font since some characters in Karen are not in Unicode but it would at least not mess with missing translations and `moment` text. This would however require additional effort from the translator and I haven't verified with them that this is a valid solution.

### CODE REVIEW

**Comment by experimatt** [comment]
@benjifs is this ready for review/to be merged?

**Comment by benjifs** [comment]
Yes, sorry. forgot to change WIP when I fixed the deploy. The comments above still stand and the translations wont all work based on how the font works.

**Comment by experimatt** [comment]
@benjifs I think having _something_ for Karen is better than nothing, and will merge this as-is. But I'd like to get @andyinabox, @caseyhelbling, or someone else's perspective on the font issues you outlined above because I'm less familiar with the translation side of things than others are.

**Comment by experimatt** [comment]
I just created a separate issue for any follow up tasks that are warranted after other folks chime in. @benjifs or whoever - feel free to close the issue and/or add more detail once a consensus is reached. https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/191

**Pull request merged**
