### PR TITLE
Replace generic markers with labelled dots

### PR DESCRIPTION
**Pull request by samanpwbb**
### What

Screen Shot 2020-06-04 at 12 59 05 AM

This pull request does the following:
- [ux] replaces teardrop-shaped html markers with GL markers that have text labels and round icons.
- [ux] updates indicator styles in sidebar to look similar to round icons.
- [ux] uses the same colors proposed in https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/50 for markers (so this PR is blocked by that PR)
- [refactor] uses geoJSON as the underlying data structure that powers the app, converts marker code to use a mapbox gl symbol layer. 

### Why

Closes https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/2 and https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/8.

Note that this PR does change some internals quite a bit – I think we should only merge this if other folks are comfortable with some of the new concepts the PR introduces because I'd hate make the app more fragile / complex just for nicer map markers.

### Ensure the following interactions work as expected. Please test using a mobile form factor.
- [x] Tapping on a marker on the map displays information about the marker in a popup.
- [x]  Tapping the "Show list of locations" button replaces the map view with a list view.
- [x] Tapping an item in the list replaces the list view with a map view, and navigates the map to the tapped item on the map.
- [x] Tapping one of the ✅'s in the legend filters items on the map and in the list.

### Check the app in the following web browsers:
- [x] Chrome
- [x] Firefox
- [ ] Edge (😬 )
- [x] Safari

### CODE REVIEW

**Comment by estherrose046** [comment]
I definitely like the circular markers, and the place-name labels!

My thoughts: 
- The color seems off between the legend and the map-markers. 
- The markers could be a bit bigger - easier to tap. 
- The markers appear and disappear at different zoom levels. Would it be possible to have the markers always be visible, but the place-labels only be visible when they don't overlap eachother? This would encourage users to zoom in more to view labels, and would also more accurately reflect site density and the sites in each neighborhood.

**Comment by samanpwbb** [comment]
@estherrose046 dealing with density is a bit tricky. I just pushed a commit that allows symbols to overlap and only shows text if there's room for text. Now looks like this:

Screen Shot 2020-06-04 at 10 43 17 AM

If I always show text without collision detection, the map gets too chaotic:

Screen Shot 2020-06-04 at 10 38 45 AM

Another option is to bring back clustering (see https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/2#issuecomment-638592307)

**Comment by samanpwbb** [comment]
https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/50 was closed so this PR also should be put on hold until we get some signal that it's actually going to solve a real problem.

**Comment by caseyhelbling** [comment]
Dropped a note to not merge yet until we fully flush this out.

**Comment by jdalt** [comment]
I think we should revert the legend to the current the colors.

I like the changes in this PR - especially being able to see the place names.

I wonder if we could use this approach as a base to add more information to the markers - like a `$` for needs money and maybe some other sort of icon for volunteers needed or an `!` for urgent needs. It seems like this is a more rich and flexible way to represent each site.

**Comment by samanpwbb** [comment]
Oh if there's still interest here, I can pick this PR back up tomorrow and get it to a merge-able state. TODO:

- [ ] Catch up to master, resolve conflicts, make work with snowpack
- [ ] Use correct colors
- [ ] Finalize approach to representing points on the map (@jdalt @estherrose046 do you two like the latest version at the staging site will work, (https://deploy-preview-64--wonderful-montalcini-96d80d.netlify.app/)).

> I wonder if we could use this approach as a base to add more information to the markers - like a `$` for needs money and maybe some other sort of icon for volunteers needed or an `!` for urgent needs. It seems like this is a more rich and flexible way to represent each site.

In order to get this merged  in a timely manner we should not add more info to markers (that can be a follow-up and I can detail a few approaches to how to do this).

**Comment by benjifs** [comment]
@samanpwbb Not sure what the solution on our end would be but on Firefox having the setting `privacy.resistFingerprinting` as `true` gives me the following:

Screen Shot 2020-06-06 at 3 38 03 PM

Setting it to false fixes it.

**Comment by samanpwbb** [comment]
> privacy.resistFingerprinting

@benjifs – I hadn't heard of this Firefox feature before – based on a quick Google search (https://wiki.mozilla.org/Security/Fingerprinting#Canvas_Fingerprinting_Detection), it looks like this setting blocks or obscures user from loading images in a canvas element. Since the map is canvas, and the markers are images, this might be a difficult edge case to support.

**Comment by jdalt** [comment]
@samanpwbb I'd like to move forward on this but I want to get verification from the organizing side, and I don't have much bandwidth to facilitate this communication in the next couple hours. I'll see if we can crowd source it.

I'm not able to view the staging link https://deploy-preview-64--wonderful-montalcini-96d80d.netlify.app/ due to some data issue.

Twin_Cities_Aid_Distribution_Locations

Given that this doesn't happen happen in prod right now, I imagine that a later PR made us more resilient.

**Comment by crhistianramirez** [comment]
> I'm not able to view the staging link https://deploy-preview-64--wonderful-montalcini-96d80d.netlify.app/ due to some data issue.

@jdalt Totally not relevant but I noticed you referenced a netlify link. Does each PR have its own deployed preview?

**Comment by jdalt** [comment]
@crhistianramirez Yes. Each PR gets an independent environment. We're living in the continuous delivery and QA isolation dream here. I want to bring this to my workplace so bad.

**Comment by samanpwbb** [comment]
I don't think this PR should be merged. It adds maintenance burden for developers, and is a UI change for folks who have come to rely on the tool. Even though it is an improvement, I'm not sure it's the right thing for a project that already "works". I would consider revisiting this if this project takes on a long-term form in the future, but I think it'd be best to close for now. @jdalt how does that sound to you?

**Comment by jdalt** [comment]
@samanpwbb I agree. I would really like place labels on the map, but I think it would probably be best at this point to pluck changes/ideas from this PR into future issues as they arise. Thanks for showing us how to do these things!

**Pull request closed without merging**
