### PR TITLE
Containerize

### PR DESCRIPTION
**Pull request by rosspenna**
### What
Added `Dockerfile` and scripts to build/run docker image/container locally.

### Why
#227 
( replaces https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/253 )

### Ensure the following interactions work as expected. Please test using a mobile form factor.
- [x] Tapping on a marker on the map displays information about the marker in a popup.
- [ ] Tapping the "Show list of locations" button replaces the map view with a list view.
- [x] Tapping an item in the list replaces the list view with a map view, and navigates the map to the tapped item on the map.
- [x] Tapping one of the ✅'s in the legend filters items on the map and in the list.
- [x] Changing the language to spanish changes things on the page.
- [x] Clicking the Help/Info button opens and closes a menu with information.
- [x] Clicking the X Close button on the Help/Info screen closes the modal.

### Check the app in the following web browsers:
- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari

### CODE REVIEW

**Comment by amaxama** [comment]
@adyates I think you reviewed @rosspenna 's first PR to containerize, would you mind taking a 👀  at this one? I believe it's pretty much the same - just created from a clone rather than fork.

**Review by adyates — APPROVED** [review]
LGTM! Looks like what I remember =)

**Comment by amaxama** [comment]
@rosspenna Looks like you just need a master merge and then should be good to go! The review might be dismissed when you do that but I can approve it if that happens!

**Review by amaxama — COMMENTED** [review]
Looks like you just need a master merge and then should be good to go! The review might be dismissed when you do that but I can approve it if that happens!

**Review by adyates — APPROVED** [review]
Re-LGTM

**Review by amaxama — APPROVED** [review]

**Pull request merged**
