### PR TITLE
render phone numbers and email addresses as links

### PR DESCRIPTION
**Pull request by eostrom**
# What
Find phone numbers and email addresses in any field where we're already finding URLs (accepting, not accepting, seeking volunteers, urgent need, notes), and render them as `tel:` and `mailto:` links.

I also split a really long and unreadable regexp into three somewhat shorter and slightly less unreadable regexps.

### Why
Implements #183. Makes it easier for map viewers to contact aid sites.

### Ensure the following interactions work as expected. Please test using a mobile form factor.
- [x] Tapping on a marker on the map displays information about the marker in a popup.
- [x] Tapping the "Show list of locations" button replaces the map view with a list view.
- [x] Tapping an item in the list replaces the list view with a map view, and navigates the map to the tapped item on the map.
- [x] Tapping one of the ✅'s in the legend filters items on the map and in the list.
- [x] Changing the language to spanish changes things on the page.
- [x] Clicking the Help/Info button opens and closes a menu with information.
- [x] Clicking the X Close button on the Help/Info screen closes the modal.

### Check the app in the following web browsers:
- [x] Chrome
- [x] Firefox
- [ ] Edge
- [x] Safari

### CODE REVIEW

**Comment by eostrom** [comment]
Known issues:

- The email regexp won't detect all valid email addresses. (No regular expression will.) It will detect almost all addresses in practical use today.
- The phone regexp detects 10-to-11-digit numbers only, and is basically "digits and punctuation," so it will pick up some false positives like "1,2,3,4,5,6,7,8,9,10."
- The code that detects URLs is separate from the less sophisticated code that decides what kind of URLs they are, so there are some theoretical cases where they could be mismatched. Doing this better would require more code restructuring than I was comfortable with at this point.
- While creating the PR, I discovered Safari doesn't detect phone numbers, using the same regexp as Firefox and Chrome. I investigated for a while, but I'm out of volunteer time for this weekend, so I'm going to leave it here. Since it adds phone links on other browsers and email links on all browsers, I think it's still worth merging, even with Safari phone numbers as an outstanding issue.

**Comment by comeoneileen** [comment]
This is awesome! Thanks for the detailed writeup - it's very clear.

I did quite a bit of testing various emails, URLs, and phone numbers tonight, and I didn't find anything that didn't work or didn't turn into the right kind of link.

**Comment by eostrom** [comment]
Short on time again this weekend, but what needs to happen to get this merged?

**Comment by estherrose046** [comment]
@eostrom it looks like it is failing the Travis CI build, but I'll look into this and try to get it merged ASAP! Thank you for this update!!

**Pull request merged**
