### PR TITLE
Add support for filtering markers, implements #6 and possibly #7

### PR DESCRIPTION
**Pull request by kmarekspartz**
Also, some automated whitespace cleanup, and include package-lock.json so we're on the same version of deps.

### CODE REVIEW

**Comment by jdalt** [comment]
Seeing this in the staging env - https://deploy-preview-34--wonderful-montalcini-96d80d.netlify.app/ 
Twin_Cities_Aid_Distribution_Locations

**Comment by kmarekspartz** [comment]
Looking into a fix

**Comment by kmarekspartz** [comment]
Fix pushed 
image

**Comment by kmarekspartz** [comment]
Closing in favor of #35, though we may want the status in the popup from this.

**Pull request closed without merging**
