### PR TITLE
Add search functionality

### PR DESCRIPTION
**Pull request by crhistianramirez**
### What
This is a re-opening of previous pull request https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/144 which I accidentally merged in and had to revert. Please refer to it for context and feedback

### Why
Helps users find locations they're interested more easily

Resolves part of #127 

### Ensure the following interactions work as expected. Please test using a mobile form factor.
- [x] Tapping on a marker on the map displays information about the marker in a popup.
- [x] Tapping the "Show list of locations" button replaces the map view with a list view.
- [x] Tapping an item in the list replaces the list view with a map view, and navigates the map to the tapped item on the map.
- [x] Tapping one of the ✅'s in the legend filters items on the map and in the list.
- [x] Changing the language to spanish changes things on the page.
- [x] Clicking the Help/Info button opens and closes a menu with information.
- [x] Clicking the X Close button on the Help/Info screen closes the modal.

### Check the app in the following web browsers:
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari

### CODE REVIEW

**Comment by crhistianramirez** [comment]
@jdalt @estherrose046 @drewsteff 

Tagging you three as you had commented on the original pull request (which I accidentally merged and had to revert). I had responded to most feedback so feel free to check it out if you haven't since then. 

I think most things are addressed but the UI still has some rough edges which I plan on improving. In the mean time if you have any other suggestions (especially related to design) please comment here :)

**Comment by crhistianramirez** [comment]
Looking into some issues around expected results not returning from search

**Comment by jdalt** [comment]
@crhistianramirez Thank you so much for seeing this through.

**Comment by estherrose046** [comment]
Hey @crhistianramirez, finally figured out what was funky with the search! We narrowed it down to the seekingVolunteers column, and then realized that the search wasn't working whenever the "seeking volunteers" badge was showing up. Fiiiiinally we realized it was because there was a class name collision! searchOn was getting the 'seekingVolunteers' class name twice, since it was both in the badge and in the hiddenFields. We changed the class name of the badge, and now it works. 

https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/156/commits/d94ab535eabddc6feface9bac9d3adcf059a86d7

**Pull request merged**
