### PR TITLE
Add support email link

### PR DESCRIPTION
**Pull request by alexives**
Fixes https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/37

Screenshot:

Screen Shot 2020-06-03 at 4 28 28 PM

### CODE REVIEW

**Comment by jdalt** [comment]
@alexives I don't think we have anything behind that email address yet. @mc-funk is there a place to forward this to yet?

**Comment by alexives** [comment]
Ah, no worries, it was labeled as high priority and seemed easy so I figured I'd knock a thing out 😂 Feel free to close if you want to hold of or whatever!

**Comment by mc-funk** [comment]
Yes we can do this with support@tcmap.org! Right now it just goes to me, but since I control the forwarding we can evolve that.

**Comment by mc-funk** [comment]
Also I love this placement of the link A LOT.

**Comment by alexives** [comment]
> Yes we can do this with [support@tcmap.org](mailto:support@tcmap.org)! Right now it just goes to me, but since I control the forwarding we can evolve that.

Done!

**Comment by experimatt** [comment]
Nice work, Alex! 🙌

**Pull request merged**
