### PR TITLE
Add Hindi and update Language Translation docs

### PR DESCRIPTION
**Pull request by kmarekspartz**
### What
Add Hindi and update Language Translation docs

### Why
1. Increases accessibility for Hindi speakers
2. Improves Language Translation process

## TODO:

[ ] Finish copypasting from the spreadsheet into the JSON... is there a script for this?

### Ensure the following interactions work as expected. Please test using a mobile form factor.
- [ ] Tapping on a marker on the map displays information about the marker in a popup.
- [ ] Tapping the "Show list of locations" button replaces the map view with a list view.
- [ ] Tapping an item in the list replaces the list view with a map view, and navigates the map to the tapped item on the map.
- [ ] Tapping one of the ✅'s in the legend filters items on the map and in the list.
- [ ] Changing the language to spanish changes things on the page.
- [ ] Clicking the Help/Info button opens and closes a menu with information.
- [ ] Clicking the X Close button on the Help/Info screen closes the modal.

### Check the app in the following web browsers:
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari

### CODE REVIEW

**Comment by experimatt** [comment]
@kmarekspartz I presume this isn't ready for merge yet :)

**Comment by kmarekspartz** [comment]
Nope, have yet to find the time to get back to this. I think Benji’s translation doc updates should be merged first, and the Hindi changes extracted from this without doc updates but with all the rows from the spreadsheet.... anyone have a handy script for that last part?

–
Kyle Marek-Spartz

**Comment by experimatt** [comment]
@kmarekspartz got it. Nope, no script as far as I know. You should write one 😉

**Comment by kmarekspartz** [comment]
Script created! I think this is ready for review again. I can't remove the label saying not to merge.

**Comment by kmarekspartz** [comment]
Travis Errors seem to be due to a missing mapbox key, unrelated to this change.

**Comment by experimatt** [comment]
@kmarekspartz label removed

**Pull request merged**
