### PR TITLE
Adds count to statusOptions

### PR DESCRIPTION
**Pull request by laniehei**
### What
This adds the count of each of the statusOptions available, as per issue #80

### Why
_What problem does this pull requests solve?  Reference related issues if appropriate._

### Ensure the following interactions work as expected. Please test using a mobile form factor.
- [x] Tapping on a marker on the map displays information about the marker in a popup.
- [ ] Tapping the "Show list of locations" button replaces the map view with a list view.
**I don't see this button in production**

- [ ] Tapping an item in the list replaces the list view with a map view, and navigates the map to the tapped item on the map.
**I don't see this button in production**

- [x] Tapping one of the ✅'s in the legend filters items on the map and in the list.
- [] Changing the language to spanish changes things on the page.
**This is a more recent change that my fork doesn't have, but I didn't change anything to do with this.** 

- [x] Clicking the Help/Info button opens and closes a menu with information.
- [x] Clicking the X Close button on the Help/Info screen closes the modal.

### Check the app in the following web browsers:
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [x] Safari

### CODE REVIEW

**Comment by estherrose046** [comment]
YES, I like this!

**Comment by laniehei** [comment]
Do not merge -- need to get .env file and fix merge conflicts. Mentioned in the Slack.

**Comment by jdalt** [comment]
>  Tapping the "Show list of locations" button replaces the map view with a list view.
> I don't see this button in production

You might need to activate the responsive view in the web tools:
Twin_Cities_Aid_Distribution_Locations

**Comment by laniehei** [comment]
closing PR -- opening a PR within the org: https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/129

**Pull request closed without merging**
