### PR TITLE
Add location schema validation

### LINKED ISSUE #92: Data validation
I think it would be good if we had a module dedicated to validating the data we're getting from Google and raising detailed errors that make it easy for us to identify where the problem is. Combined with #91 this could go a long way toward avoiding lengthy outages.

### PR DESCRIPTION
**Pull request by cwood821**
### What
Add schema validation to incoming data from Google Sheets, filters out potential TypeError-causing rows, and logs specific row and column information. Resolves #92. 

### Why
We've seen type errors pop up when working with Google Sheets data as volunteers change, update, or remove data. This PR creates a system for type checking incoming data to improve stability.

### Ensure the following interactions work as expected. Please test using a mobile form factor.
- [x] Tapping on a marker on the map displays information about the marker in a popup.
- [x] Tapping the "Show list of locations" button replaces the map view with a list view.
- [x] Tapping an item in the list replaces the list view with a map view, and navigates the map to the tapped item on the map.
- [x] Tapping one of the ✅'s in the legend filters items on the map and in the list.
- [x] Changing the language to spanish changes things on the page.
- [x] Clicking the Help/Info button opens and closes a menu with information.
- [x] Clicking the X Close button on the Help/Info screen closes the modal.

### Check the app in the following web browsers:
- [x] Chrome
- [x] Firefox
- [ ] Edge
- [x] Safari

### CODE REVIEW

**Comment by jdalt** [comment]
Just had a moment to skim this before bed. I really like where it's going. Have you considered using something like JSON Schema to perform the validation?

**Comment by cwood821** [comment]
@jdalt I haven't used JSON schema before in a client side context, but I like that idea rather than creating a new format. I'll do some searching to see if there are decent libraries.

**Comment by jdalt** [comment]
@cwood821 I've also never taken JSON schema all the way to the Frontend, but I've really enjoyed using it on the backend. It's declarative and you can potentially share a public version of the schema. I've seen [other projects](https://github.com/radiantearth/stac-spec/tree/master/item-spec) use JSON schema to drive a spec. If we wanted to give other folks api access, this would probably help communicate what we were offering.

**Comment by cwood821** [comment]
@jdalt I've updated the code to use JSON schema and output any errors. At the moment, everything is a string because Google Sheets wraps every value as a string. This is limits type errors that it catches, but it will definitely log if the json is malformed. 

If desired (and I might just do this regardless), I'll look into how the library I added might be extended to support custom validation for stuff like lat and lng points to make it a bit more robust. That could be a separate issue, though, if you'd prefer to merge this sooner.

**Comment by jdalt** [comment]
@cwood821 I think this is a good start and if we use an api shim we might move this there. I think you might be able to push the rigor/strictness of the the schema a bit further. You could apply a format regex here and there - I think we've gotten burnt by invalid `color` values once or twice. Might be nice to verify we get a hex value there.

I think your intuition about extending to lat and lng is correct. Let's get this merged first and go from there.

It looks like other PRs that I've merged tonight have caused a conflict. Feel free to ping me once you've merged master, and I'll take another look.

**Comment by cwood821** [comment]
@jdalt Merge conflict should be sorted now. Thanks!

**Pull request merged**
